# Generated by Django 4.2 on 2023-11-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_yes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='option',
            name='status',
            field=models.CharField(choices=[('GREEN', 'Green'), ('AMBER', 'Amber'), ('RED', 'Red')], default='GREEN', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'is_yes')},
        ),
        migrations.RemoveField(
            model_name='option',
            name='text',
        ),
        migrations.RemoveField(
            model_name='option',
            name='triggers_file_upload',
        ),
        migrations.RemoveField(
            model_name='option',
            name='triggers_text_input',
        ),
    ]
