# Generated by Django 4.2 on 2023-11-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_option_is_yes_option_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='no_triggers_text_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='yes_triggers_file_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_yes',
            field=models.BooleanField(),
        ),
        migrations.RemoveField(
            model_name='option',
            name='status',
        ),
    ]
