# Generated by Django 4.2 on 2023-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_alter_option_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_yes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='no_triggers_text_input',
        ),
        migrations.RemoveField(
            model_name='question',
            name='yes_triggers_file_upload',
        ),
        migrations.AddField(
            model_name='option',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='triggers_file_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='triggers_text_input',
            field=models.BooleanField(default=False),
        ),
    ]
