# Generated by Django 4.2 on 2023-11-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_remove_option_is_yes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='option',
            name='status',
            field=models.CharField(choices=[('GREEN', 'Green'), ('AMBER', 'Amber'), ('RED', 'Red')], default='GREEN', max_length=5),
        ),
        migrations.AddField(
            model_name='option',
            name='triggers_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_options', to='app_core.question')),
            ],
        ),
    ]
