# Generated by Django 4.2 on 2023-11-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_option_triggers_date_picker'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoDropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_dropdown_options', to='app_core.question')),
            ],
        ),
        migrations.CreateModel(
            name='YesDropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yes_dropdown_options', to='app_core.question')),
            ],
        ),
        migrations.RenameField(
            model_name='option',
            old_name='triggers_dropdown',
            new_name='triggers_no_dropdown',
        ),
        migrations.AddField(
            model_name='option',
            name='triggers_yes_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DropdownOption',
        ),
    ]
