# Generated by Django 4.2 on 2023-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_nodropdownoption_yesdropdownoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='text',
        ),
        migrations.AddField(
            model_name='option',
            name='custom_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('CUSTOM', 'Custom')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
