# Generated by Django 4.2 on 2023-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_remove_option_text_option_custom_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='mandatory',
            field=models.BooleanField(default=False, help_text='Mark this option as mandatory'),
        ),
    ]
